// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fxhealth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	fxhealth.proto

It has these top-level messages:
	FxHealth
*/
package proto

import (
	fmt "fmt"

	proto1 "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type FxHealth struct {
}

func (m *FxHealth) Reset()                    { *m = FxHealth{} }
func (m *FxHealth) String() string            { return proto1.CompactTextString(m) }
func (*FxHealth) ProtoMessage()               {}
func (*FxHealth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FxHealth_PingRequest struct {
}

func (m *FxHealth_PingRequest) Reset()                    { *m = FxHealth_PingRequest{} }
func (m *FxHealth_PingRequest) String() string            { return proto1.CompactTextString(m) }
func (*FxHealth_PingRequest) ProtoMessage()               {}
func (*FxHealth_PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type FxHealth_PingResponse struct {
}

func (m *FxHealth_PingResponse) Reset()                    { *m = FxHealth_PingResponse{} }
func (m *FxHealth_PingResponse) String() string            { return proto1.CompactTextString(m) }
func (*FxHealth_PingResponse) ProtoMessage()               {}
func (*FxHealth_PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func init() {
	proto1.RegisterType((*FxHealth)(nil), "base.FxHealth")
	proto1.RegisterType((*FxHealth_PingRequest)(nil), "base.FxHealth.PingRequest")
	proto1.RegisterType((*FxHealth_PingResponse)(nil), "base.FxHealth.PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FxHealthService service

type FxHealthServiceClient interface {
	Ping(ctx context.Context, in *FxHealth_PingRequest, opts ...grpc.CallOption) (*FxHealth_PingResponse, error)
}

type fxHealthServiceClient struct {
	cc *grpc.ClientConn
}

func NewFxHealthServiceClient(cc *grpc.ClientConn) FxHealthServiceClient {
	return &fxHealthServiceClient{cc}
}

func (c *fxHealthServiceClient) Ping(ctx context.Context, in *FxHealth_PingRequest, opts ...grpc.CallOption) (*FxHealth_PingResponse, error) {
	out := new(FxHealth_PingResponse)
	err := grpc.Invoke(ctx, "/base.FxHealthService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FxHealthService service

type FxHealthServiceServer interface {
	Ping(context.Context, *FxHealth_PingRequest) (*FxHealth_PingResponse, error)
}

func RegisterFxHealthServiceServer(s *grpc.Server, srv FxHealthServiceServer) {
	s.RegisterService(&_FxHealthService_serviceDesc, srv)
}

func _FxHealthService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FxHealth_PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxHealthServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.FxHealthService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxHealthServiceServer).Ping(ctx, req.(*FxHealth_PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FxHealthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.FxHealthService",
	HandlerType: (*FxHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FxHealthService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fxhealth.proto",
}

func init() { proto1.RegisterFile("fxhealth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xab, 0xc8, 0x48,
	0x4d, 0xcc, 0x29, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x4a, 0x2c, 0x4e,
	0x55, 0xd2, 0xe4, 0xe2, 0x70, 0xab, 0xf0, 0x00, 0x8b, 0x4b, 0xf1, 0x72, 0x71, 0x07, 0x64, 0xe6,
	0xa5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x48, 0xf1, 0x71, 0xf1, 0x40, 0xb8, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x46, 0x21, 0x5c, 0xfc, 0x30, 0xa5, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9,
	0xa9, 0x42, 0x8e, 0x5c, 0x2c, 0x20, 0x25, 0x42, 0x52, 0x7a, 0x20, 0xc3, 0xf4, 0x60, 0xd2, 0x7a,
	0xc8, 0xc6, 0x48, 0x63, 0x95, 0x83, 0x98, 0xa9, 0xc4, 0xe0, 0xa4, 0x18, 0x25, 0x9f, 0x9e, 0x9f,
	0x93, 0x98, 0x97, 0xae, 0x97, 0x9e, 0x58, 0x94, 0x9a, 0x97, 0xa8, 0x97, 0x9c, 0x9f, 0xab, 0x9f,
	0x56, 0xa1, 0x9f, 0x5e, 0x54, 0x90, 0xac, 0x0f, 0x76, 0x69, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0xfc, 0xfc, 0x97, 0xc2, 0x00, 0x00, 0x00,
}
